### ISSUE TITLE
Missing/ Incomplete functions

### ISSUE THREAD

**Issue by hieu2102** [hacktiger/MyProject#1]
- [x] Check game before show
- [x] remove tags from games ( in edit --will fix to display already chosen ones in the future)
- [x] Password Reset

**Comment by hieu2102** [comment]
+ java script / bootstrap install

**Comment by hieu2102** [comment]
+ missing default covers, avatars
+ ProfileController@update: can't store image at local directory (public/avatars)

**Comment by hacktiger** [comment]
nice su

**Comment by hacktiger** [comment]
t redesign lại admin cho

**Comment by hacktiger** [comment]
user name unique lam gi co email unique r

**Comment by hieu2102** [comment]
thường có ai check email đúng đâu
that's how scam happened m8

**Comment by hieu2102** [comment]
test sơ qua thì xong rồi, còn mỗi reset password bị lỗi màn hình đen thôi
